# Generated by Django 4.1.5 on 2024-02-01 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0002_alter_invoicedetail_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="customer_name",
            field=models.CharField(max_length=255, verbose_name="Invoice CustomerName"),
        ),
        migrations.AlterField(
            model_name="invoicedetail",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="invoices.invoice"
            ),
        ),
        migrations.AlterField(
            model_name="invoicedetail",
            name="price",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
